name: Test Build Virtual Delay
on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up MSYS2 with compilers and FLTK
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-fltk
            make

      - name: Compile Application Natively
        shell: msys2 {0}
        run: |
          g++ -O2 -Wall virtualdelay.cpp resource.res -o VirtualDelay.exe `fltk-config --cxxflags --ldstaticflags` -lole32 -luuid -lcomctl32 -lws2_32 -mwindows
